remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

  minimal_mistakes_skin    : "contrast" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


title: Fortyninebagels
description: 

author:
  name: "Baegel"
  bio: "The dough of 49 bagels maketh a man"

#navigation_main:
#  - title: "Blog"
#    url: /blog/
#  - title: "Wiki"
#    url: /wiki/
#  - title: "About"
#    url: /about/
