remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

title: Fortyninebagels
description: 

# Site Author
author:
  name: "Baegel"
  bio: "The dough of 49 bagels maketh a man"

# Navigation
navigation: true

navigation:
  - title: "Blog"
    url: /blog/
  - title: "Wiki"
    url: /wiki/
  - title: "About"
    url: /about/
